# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
def networking
  pod 'Moya'
end

target 'VIPER-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  networking
  
  # Pods for VIPER-Demo

  target 'VIPER-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VIPER-DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
